apiVersion: batch/v1
kind: CronJob
metadata:
  name: delete-flask-pods
spec:
  schedule: "{{ .Values.cronjob.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: pod-cleaner
          containers:
            - name: cleaner
              image: bitnami/kubectl
              command:
                - /bin/sh
                - -c
                - kubectl delete pod -l app.kubernetes.io/name=flask-app
          restartPolicy: OnFailure